# Generated by Django 3.2.4 on 2021-06-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='firm_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
