# Generated by Django 3.2.4 on 2021-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyledger', '0003_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
